en:
    blog.category.headline: 'Blog'
    blog.category.title: 'Blog category'
    blog.category.not_found: 'Category not found. Please continue to'
    blog.category.all_posts: 'list of all posts'
    blog.post.not_found: 'Post not found. Please continue to'
    blog.post.posted: 'Posted'
    blog.post.under: 'Under'
    blog.post.by: 'By'
    section.contact.headline: 'Contact Us'
    section.contact.map: 'Directions'
    section.contact.form: 'Email'
    section.contact.name: 'Name'
    section.contact.email: 'Email'
    section.contact.phone: 'Phone'
    section.contact.message: 'Message'
    section.contact.button: 'Send'
    section.cta.heading: 'WITH VEGA IMAGINATION IS YOUR ONLY LIMIT!'
    section.cta.button: 'Theme homepage'
    section.cta2.button: 'Upgrade to Pro'
    section.features.headline: 'Featured Pages'
    section.features.more: 'Learn More'
    section.intro.headline: 'ONE PAGE BUSINESS THEME'
    section.intro.button: 'View More'
    section.posts.headline: 'Latest Posts'
    section.posts.more: 'View more posts'
    section.welcome.headline: 'Welcome to Vega'
    section.welcome.button: 'Download Latest Version'
    sidebar.search.title: 'Search'
    sidebar.search.placeholder: 'Search...'
    sidebar.about.title: 'About Me'
    sidebar.recent.title: 'Recent Posts'
    sidebar.tags.title: 'Tags'
    footer.header.first: 'About Vega lite'
    footer.header.second: 'Categories'
    footer.header.third: 'Contact Us'
    footer.header.fourth: 'Follow Us'
    footer.facebook.like_us: 'Like Us'
cs:
    blog.category.headline: 'Články'
    blog.category.title: 'Kategorie článků'
    blog.category.not_found: 'Kategorie nenalezena. Prosím pokračujte na'
    blog.category.all_posts: 'seznam všech článků'
    blog.post.not_found: 'Článek nenalezen. Prosím pokračujte na'
    blog.post.posted: 'Zveřejněno'
    blog.post.under: 'V kategoriích'
    blog.post.by: 'Autor'
    section.contact.headline: 'Kontaktujte nás'
    section.contact.map: 'Jak se k nám dostanete'
    section.contact.form: 'E-mail'
    section.contact.name: 'Jméno a příjmení'
    section.contact.email: 'E-mailová adresa'
    section.contact.phone: 'Telefon'
    section.contact.message: 'Zpráva'
    section.contact.button: 'Odeslat'
    section.cta.heading: 'WITH VEGA IMAGINATION IS YOUR ONLY LIMIT!'
    section.cta.button: 'Domovská stránka'
    section.cta2.button: 'Upgrade to Pro'
    section.features.headline: 'Výhody'
    section.features.more: 'Více'
    section.intro.headline: 'ONE PAGE BUSINESS THEME'
    section.intro.button: 'View More'
    section.posts.headline: 'Blog'
    section.posts.more: 'Více článků'
    section.welcome.headline: 'Welcome to Vega'
    section.welcome.button: 'Stáhnout poslední verzi'
    sidebar.search.title: 'Vyhledávání'
    sidebar.search.placeholder: 'Hledat...'
    sidebar.about.title: 'O mně'
    sidebar.recent.title: 'Poslední články'
    sidebar.tags.title: 'Tagy'
    footer.header.first: 'O nás'
    footer.header.second: 'Kategorie blogu'
    footer.header.third: 'Kontaktujte nás'
    footer.header.fourth: 'Sledujte nás'
    footer.facebook.like_us: 'Lajkujte nás'
pl:
    blog.category.headline: 'Posty'
    blog.category.title: 'Kategorie postów'
    blog.category.not_found: 'Znaleziono kategorii. Proszę kontynuować'
    blog.category.all_posts: 'lista wszystkich postów'
    blog.post.not_found: 'Nie został znaleziony. Proszę kontynuować'
    blog.post.posted: 'Opublikowany'
    blog.post.under: 'W kategoriach'
    blog.post.by: 'Autor'
    section.contact.headline: 'Skontaktuj się ze mną'
    section.contact.map: 'Jak dojechać'
    section.contact.form: 'E-mail'
    section.contact.name: 'Imię'
    section.contact.email: 'E-mail'
    section.contact.phone: 'Telefon'
    section.contact.message: 'Twoja wiadomość'
    section.contact.button: 'Wyślij'
    section.cta.heading: 'WITH VEGA IMAGINATION IS YOUR ONLY LIMIT!'
    section.cta.button: 'Strona główna'
    section.cta2.button: 'Upgrade to Pro'
    section.features.headline: 'Cechy'
    section.features.more: 'Jeszcze'
    section.intro.headline: 'ONE PAGE BUSINESS THEME'
    section.intro.button: 'Zobacz więcej'
    section.posts.headline: 'Posty'
    section.posts.more: 'Więcej postów'
    section.welcome.headline: 'Welcome to Vega'
    section.welcome.button: 'Pobierz najnowszą wersję'
    sidebar.search.title: 'Poszukiwanie'
    sidebar.search.placeholder: 'Wyglądać...'
    sidebar.about.title: 'O mnie'
    sidebar.recent.title: 'Najnowsze posty'
    sidebar.tags.title: 'Tagi'
    footer.header.first: 'O nas'
    footer.header.second: 'Kategorie bloga'
    footer.header.third: 'Skontaktuj się ze mną'
    footer.header.fourth: 'Śledź nas'
    footer.facebook.like_us: 'Jak my'